% GENDOC Generate documentation for CJFSandBox
% use Graphviz
% addpath ('ext/m2html')
% gendoc

%  $Author: Corey Flynn, Rajiv Narayan Broad Institute 2011

function cjfSandboxGenDoc
%log the starting path
start_path = pwd;

%add the path to m2html
addpath('/xchip/cogs/tools/bmtk/ext/m2html');

cd('/xchip/cogs/cflynn/');
m2html ('mfiles', 'sandboxCodeWorking/matlab/', ...
    'htmldir', 'matlabDoc',...
    'recursive','on',...
    'source','on',...
    'syntaxhighlighting','on',...
    'tabs',4,...
    'globalHypertextLinks','on',...
    'graph','on',...
    'save','on',...
    'indexfile','index',...
    'extension','.html',...
    'template','blue')