function multi_colored_uitable
% Create a figure
f = figure;

% Define the column names
colnames = {'first', '', 'third', 'fourth'};

% Create a cell array with HTML code
celldata = {colText('Red text', 'red'), ...
colText('1', 'blue'), ...
colText('Green text', 'green'), ...
colText('Purple text', 'purple')};

% Create a uitable with one row and 4 columns and colored cells
uitable(f, 'Data', celldata, ...
'ColumnName', colnames, ...
'Units', 'normalized', ...
'Position', [0 0 1 1]);
end

function outHtml = colText(inText, inColor)
% return a HTML string with colored font
outHtml = ['<html><font bgcolor="', ...
inColor, ...
'">', ...
inText, ...
'</font></html>'];
end